### ISSUE TITLE
AttributeError: 'TwoFactorAuthClient' object has no attribute 'client'

### ISSUE THREAD

**Issue by evgenybf** [Bandwidth-Samples/mfa-cli-python#2]
It seems that `requirements.txt` should contain a version of bandwidth-sdk that should be used to run the example. After installing, `app.py` fails as the `.client` property in the `TwoFactorAuthClient` class has been replaced with `.mfa`:

Old:
```python
auth_client = bandwidth_client.two_factor_auth_client.client
```

New:
```python
auth_client = bandwidth_client.two_factor_auth_client.mfa
```

**Comment by jmulford-bw** [comment]
Hey @evgenybf thanks for bringing this up. You're indeed correct and this is fixed with https://github.com/Bandwidth-Samples/2fa-cli-python/pull/3. We'll push an initiative to clean this up across our other samples too. Thanks!
